### PR TITLE
Left nav implementation

### PR DESCRIPTION
**Pull request by emmayakley**
Added a component on the left that displays the username and link to repository, number of repos, followers, and following. 

Please let me know of any improvements or styling changes you think would improve this!

### CODE REVIEW

**Comment by emmayakley** [comment]
## Changes:
1. moved the search bar and dark/light toggle into the header and styled accordingly
2. Started working on the chart implementation to display the users number of languages they've used in all repositories. I don't think the code is functioning correctly, so testing needs to be done and improvements need to be made.

**Comment by emmayakley** [comment]
## What I changed
I added 2 components: 
ChartDisplay: Each repository in a users account has a language that was the most used. This pie chart displays the amount of times each language is the top language for all of the users repos.
TopStars:  This bar graph shows the users top 5 repositories with the most stars and the amount of stars the repo has.

## What feedback I'm looking for:
Neither of these components have been styled yet. They both appear to the right of the table that displays followers, following, repos, and number of forks. Also, the implementation of TopStars is not correct. Right now the bar graph renders but the actual bars do not show up (something with the parsing of data is incorrect). I'm not sure if the table should table should take up less space and the graphs should appear to the right of it, or if they should appear below the table. Any suggestions on styling is much appreciated!

**Comment by mukundsai79** [comment]
> Added a component on the left that displays the username and link to repository, number of repos, followers, and following.
> 
> Please let me know of any improvements or styling changes you think would improve this!

can you also please add the number of forks content display

**Comment by emmayakley** [comment]
## Changes I made
I updated the pie chart to have a title.
I updated the star count to display the data and have each bar be individually colored. 
I updated the leftNavbar component to include a sum of all of the forks over all of the users repos.

##Feedback I'm looking for
Mainly just need to style at this point, but I am waiting for the charts tab to be added and then I will import the components and style them. Any other suggestions always welcome!

**Pull request merged**
